[2014-04-28 00:55:34] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:121
Stack trace:
#0 /home/acegroup/public_html/app/routes.php(409): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 [internal function]: {closure}('solutions')
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#4 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2014-04-28 00:55:52] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:121
Stack trace:
#0 /home/acegroup/public_html/app/routes.php(409): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 [internal function]: {closure}('solutions')
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#4 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2014-04-28 00:57:35] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:121
Stack trace:
#0 /home/acegroup/public_html/app/routes.php(409): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 [internal function]: {closure}('solutions')
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#4 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2014-04-28 00:57:43] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:121
Stack trace:
#0 /home/acegroup/public_html/app/routes.php(409): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 [internal function]: {closure}('solutions')
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#4 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2014-04-28 00:58:47] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:121
Stack trace:
#0 /home/acegroup/public_html/app/routes.php(409): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 [internal function]: {closure}('contact.php')
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#4 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2014-04-28 01:00:13] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:121
Stack trace:
#0 /home/acegroup/public_html/app/routes.php(409): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 [internal function]: {closure}('solutions')
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#4 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2014-04-28 01:00:51] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:121
Stack trace:
#0 /home/acegroup/public_html/app/routes.php(409): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 [internal function]: {closure}('admin')
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#4 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2014-04-28 01:01:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429
Stack trace:
#0 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-04-28 01:01:39] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429
Stack trace:
#0 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-04-28 01:02:31] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429
Stack trace:
#0 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-04-28 01:02:37] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429
Stack trace:
#0 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-04-28 01:03:04] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'acegroup_lsql.gy_levels' doesn't exist' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:272
Stack trace:
#0 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(272): PDO->prepare('select `id`, `n...')
#1 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select `id`, `n...', Array)
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run('select `id`, `n...', Array, Object(Closure))
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1025): Illuminate\Database\Connection->select('select `id`, `n...', Array)
#4 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1015): Illuminate\Database\Query\Builder->runSelect()
#5 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1002): Illuminate\Database\Query\Builder->getFresh(Array)
#6 /home/acegroup/public_html/app/libraries/model-helper/UserHelper.php(84): Illuminate\Database\Query\Builder->get()
#7 /home/acegroup/public_html/app/modules/banner/controllers/BannerController.php(159): UserHelper::getAllLevels()
#8 [internal function]: App\Modules\Banner\BannerController->editAction('809')
#9 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#10 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editAction', Array)
#11 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editAction', Array)
#12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('809')
#13 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#14 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#15 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#18 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#19 {main}

Next exception 'Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'acegroup_lsql.gy_levels' doesn't exist (SQL: select `id`, `name` from `gy_levels`) (Bindings: array (
))' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556
Stack trace:
#0 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select `id`, `n...', Array)
#1 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run('select `id`, `n...', Array, Object(Closure))
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1025): Illuminate\Database\Connection->select('select `id`, `n...', Array)
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1015): Illuminate\Database\Query\Builder->runSelect()
#4 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1002): Illuminate\Database\Query\Builder->getFresh(Array)
#5 /home/acegroup/public_html/app/libraries/model-helper/UserHelper.php(84): Illuminate\Database\Query\Builder->get()
#6 /home/acegroup/public_html/app/modules/banner/controllers/BannerController.php(159): UserHelper::getAllLevels()
#7 [internal function]: App\Modules\Banner\BannerController->editAction('809')
#8 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#9 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editAction', Array)
#10 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editAction', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('809')
#12 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#13 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#14 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2014-04-28 01:03:20] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429
Stack trace:
#0 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /home/acegroup/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /home/acegroup/public_html/index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
